Repository Yoctol/yoctol-nlu-py, pull requests merged in 2018-03, with the labels that each got.

#12 Modify the sdk for understood
  .travis.yml
  README.md
  requirements.txt
  setup.py
  ynlu/__init__.py
  ynlu/intent_classifier/__init__.py
  ynlu/intent_classifier/client.py
  ynlu/intent_classifier/global_variables.py
  ynlu/intent_classifier/test/__init__.py
  ynlu/intent_classifier/test/test_client.py
  ynlu/sdk/__init__.py
  ynlu/sdk/client.py
  ynlu/sdk/model.py
  ynlu/sdk/test/__init__.py
  ynlu/sdk/test/test_client.py
  ynlu/test/test_import.py
Labels: ReadyForReview

#15 Can install via pip install now
  setup.py
  ynlu/__init__.py
  ynlu/__version__.py
Labels: ReadyForReview

#17 Automatically fetch possible ids when creating the client instance
  ynlu/sdk/client.py
  ynlu/sdk/model.py
  ynlu/sdk/test/test_client.py
Labels: ReadyForReview, enhancement

#18 Fix README & support name fetching too
  README.md
  ynlu/sdk/client.py
  ynlu/sdk/test/test_client.py
Labels: ReadyForReview

#20 added flake8
  .flake8
  .travis.yml
  requirements.txt
  setup.py
  ynlu/__init__.py
  ynlu/sdk/__init__.py
  ynlu/sdk/model.py
  ynlu/sdk/test/test_client.py
Labels: ReadyForReview

#22 ignore build folder when doing flake8 check
  .flake8
Labels: ReadyForReview

#25 evaluation folder structure
  ynlu/sdk/evaluation/__init__.py
  ynlu/sdk/evaluation/entity_confusion_matrix.py
  ynlu/sdk/evaluation/intent_precision_recall.py
  ynlu/sdk/evaluation/tests/__init__.py
Labels: ReadyForReview

#29 Add test for model
  ynlu/sdk/test/test_model.py
Labels: ReadyForReview

#32 Use gql-fork
  .travis.yml
  requirements.txt
  setup.py
Labels: ReadyForReview

#33 intent topk accuracy score
  ynlu/sdk/evaluation/intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_accuracy_score.py
Labels: ReadyForReview

#34 intent topk precision score
  ynlu/sdk/evaluation/intent_topk_precision_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_precision_score.py
Labels: ReadyForReview

#36 add base exception files
  ynlu/exceptions.py
  ynlu/sdk/evaluation/exceptions.py
  ynlu/sdk/exceptions.py
Labels: ReadyForReview

#39 Batch predict return separate
  ynlu/sdk/model.py
Labels: ReadyForReview

#40 do not sort prediction result
  ynlu/sdk/model.py
  ynlu/sdk/test/test_model.py
Labels: ReadyForReview

#37 remove dev dependancy from setup
  requirements.txt
  setup.py
Labels: ReadyForReview

#41 added evaluation methods in __init__
  ynlu/sdk/evaluation/__init__.py
Labels: ReadyForReview

#42 modified entity prediction key from "name" to "entity"
  ynlu/sdk/evaluation/intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/intent_topk_precision_score.py
  ynlu/sdk/evaluation/tests/test_entity_confusion_matrix.py
  ynlu/sdk/evaluation/tests/test_entity_overlapping_ratio.py
  ynlu/sdk/evaluation/tests/test_intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_precision_score.py
  ynlu/sdk/evaluation/tests/test_utils.py
  ynlu/sdk/evaluation/utils.py
Labels: ReadyForReview

#44 added 'single__' as prefix and remove suffix 'overall'
  ynlu/sdk/evaluation/__init__.py
  ynlu/sdk/evaluation/intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/intent_topk_precision_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_precision_score.py
Labels: ReadyForReview

#45 batch version overlapping scores
  ynlu/sdk/evaluation/__init__.py
  ynlu/sdk/evaluation/entity_overlapping_score.py
  ynlu/sdk/evaluation/tests/test_entity_overlapping_ratio.py
Labels: ReadyForReview

#43 setup sphinx
  .flake8
  README.md
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/reference/modules.rst
  docs/reference/ynlu.rst
  docs/reference/ynlu.sdk.evaluation.rst
  docs/reference/ynlu.sdk.evaluation.tests.rst
  docs/reference/ynlu.sdk.rst
  docs/reference/ynlu.sdk.test.rst
  requirements.txt
Labels: ReadyForReview

#47 use mathjax instead of imgmath
  docs/conf.py
Labels: ReadyForReview

#48 entity -> intent
  ynlu/sdk/evaluation/intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/intent_topk_precision_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_accuracy_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_precision_score.py
Labels: ReadyForReview, bug

#46 added recall
  docs/reference/ynlu.sdk.evaluation.rst
  docs/reference/ynlu.sdk.evaluation.tests.rst
  ynlu/sdk/evaluation/intent_topk_recall_score.py
  ynlu/sdk/evaluation/tests/test_intent_topk_recall_score.py
Labels: ReadyForReview
